/**
 * ============================================================================
 * RESUME DOMAIN MODEL (Day 38)
 * ============================================================================
 *
 * FILE PURPOSE:
 * Canonical in-memory "ResumeDocument" object that supports:
 * - Base profile and sections (experience/education/skills/awards/etc)
 * - Narratives (federal narrative blocks / accomplishment bullets)
 * - Views (each view references included sections + formatting rules)
 * - Versions (each version references a snapshot or delta from base)
 * - TailoringState (optional: targetJobId, jobTitle, key requirements, coverage map)
 *
 * WHERE IT FITS IN PATHOS ARCHITECTURE:
 * - Frontend-only, local-only domain model
 * - Extends existing ResumeData types from lib/mock/resume-builder.ts
 * - Used by resumeBuilderStore for versioning and view management
 * - Everything MUST have safe defaults
 *
 * @version Day 38 - Resume Builder Revamp
 * ============================================================================
 */

import type {
  ResumeProfile,
  TargetRole,
  WorkExperience,
  Education,
  Skills,
} from '@/lib/mock/resume-builder';
import type { TargetJob } from '@/store/resumeBuilderStore';

/**
 * Resume View Type
 *
 * PURPOSE:
 * Defines different ways to render the same resume data.
 * Each view has its own formatting rules and section inclusion rules.
 */
export type ResumeViewType = 'federal' | 'private' | 'one-page' | 'full';

/**
 * Resume View Configuration
 *
 * PURPOSE:
 * Defines which sections are included and how they're formatted for a specific view.
 */
export interface ResumeView {
  id: string;
  type: ResumeViewType;
  label: string;
  description: string;
  includedSections: {
    profile: boolean;
    targetRoles: boolean;
    workExperience: boolean;
    education: boolean;
    skills: boolean;
    certifications: boolean;
    languages: boolean;
    ksas: boolean;
  };
  formattingRules: {
    maxLength?: number; // For one-page view
    emphasisLevel: 'high' | 'medium' | 'low';
    showQuantifiedAccomplishments: boolean;
    showDuties: boolean;
  };
}

/**
 * Resume Version
 *
 * PURPOSE:
 * Represents a named snapshot or delta from the base resume.
 * Versions are not filenames - they're named cards that users can create, rename, duplicate, and delete.
 */
export interface ResumeVersion {
  id: string;
  name: string;
  createdAt: number; // Timestamp
  updatedAt: number; // Timestamp
  isBase: boolean; // True for the base/default version
  snapshot: {
    profile: ResumeProfile;
    targetRoles: TargetRole[];
    workExperience: WorkExperience[];
    education: Education[];
    skills: Skills;
  };
  metadata: {
    description?: string;
    tags?: string[];
    tailoringJobId?: string; // If this version was tailored for a specific job
  };
}

/**
 * Tailoring State
 *
 * PURPOSE:
 * Tracks the current tailoring session for a selected job.
 * Contains target job info, key requirements, and coverage map.
 */
export interface TailoringState {
  targetJobId: string | null;
  targetJob: TargetJob | null;
  jobTitle: string;
  keyRequirements: string[]; // Extracted from job posting
  coverageMap: {
    // Maps section IDs to coverage scores (0-100)
    profile: number;
    workExperience: number;
    education: number;
    skills: number;
  };
  suggestedRewrites: SuggestedRewrite[]; // Generated by applyTailoringHints()
}

/**
 * Suggested Rewrite
 *
 * PURPOSE:
 * Represents a suggested change to a resume section (e.g., a bullet point rewrite).
 * Used by the rewrite transition UI for accept/reject.
 */
export interface SuggestedRewrite {
  id: string;
  sectionType: 'workExperience' | 'education' | 'skills' | 'profile';
  sectionId: string; // ID of the work experience item, education item, etc.
  fieldName: string; // e.g., 'accomplishments', 'duties', 'ksas'
  oldValue: string;
  newValue: string;
  reason: string; // Why this rewrite was suggested (e.g., "GS-calibrated", "USAJOBS keyword coverage")
  status: 'pending' | 'accepted' | 'rejected';
}

/**
 * Resume Document
 *
 * PURPOSE:
 * The canonical in-memory resume object that supports views, versions, and tailoring.
 * This is the single source of truth for resume state.
 */
export interface ResumeDocument {
  // Base profile and sections (shared across all versions)
  baseProfile: ResumeProfile;
  baseSections: {
    targetRoles: TargetRole[];
    workExperience: WorkExperience[];
    education: Education[];
    skills: Skills;
  };

  // Narratives (federal narrative blocks / accomplishment bullets)
  narratives: {
    federalNarrative: string; // Federal-style narrative summary
    accomplishmentBullets: string[]; // Key accomplishment bullets
  };

  // Views (each view references included sections + formatting rules)
  views: ResumeView[];
  activeViewId: string; // ID of the currently selected view

  // Versions (each version references a snapshot or delta from base)
  versions: ResumeVersion[];
  activeVersionId: string; // ID of the currently selected version

  // Tailoring state (optional: targetJobId, jobTitle, key requirements, coverage map)
  tailoringState: TailoringState | null;
}

/**
 * Default Resume View Configurations
 *
 * PURPOSE:
 * Pre-defined view configurations for common resume formats.
 */
export const DEFAULT_VIEWS: ResumeView[] = [
  {
    id: 'view-federal',
    type: 'federal',
    label: 'Federal',
    description: 'USAJOBS-compliant format with detailed duties and accomplishments',
    includedSections: {
      profile: true,
      targetRoles: true,
      workExperience: true,
      education: true,
      skills: true,
      certifications: true,
      languages: true,
      ksas: true,
    },
    formattingRules: {
      emphasisLevel: 'high',
      showQuantifiedAccomplishments: true,
      showDuties: true,
    },
  },
  {
    id: 'view-private',
    type: 'private',
    label: 'Private Sector',
    description: 'Traditional resume format for private sector applications',
    includedSections: {
      profile: true,
      targetRoles: false,
      workExperience: true,
      education: true,
      skills: true,
      certifications: true,
      languages: false,
      ksas: false,
    },
    formattingRules: {
      emphasisLevel: 'medium',
      showQuantifiedAccomplishments: true,
      showDuties: false,
    },
  },
  {
    id: 'view-one-page',
    type: 'one-page',
    label: 'One-Page',
    description: 'Condensed format for quick scanning',
    includedSections: {
      profile: true,
      targetRoles: true,
      workExperience: true,
      education: true,
      skills: true,
      certifications: false,
      languages: false,
      ksas: false,
    },
    formattingRules: {
      maxLength: 1, // 1 page
      emphasisLevel: 'high',
      showQuantifiedAccomplishments: true,
      showDuties: false,
    },
  },
  {
    id: 'view-full',
    type: 'full',
    label: 'Full',
    description: 'Complete resume with all sections and details',
    includedSections: {
      profile: true,
      targetRoles: true,
      workExperience: true,
      education: true,
      skills: true,
      certifications: true,
      languages: true,
      ksas: true,
    },
    formattingRules: {
      emphasisLevel: 'high',
      showQuantifiedAccomplishments: true,
      showDuties: true,
    },
  },
];





