/**
 * ============================================================================
 * PATHADVISOR CHANGE PROPOSALS (Day 43 - Guidance Model)
 * ============================================================================
 *
 * FILE PURPOSE:
 * Defines the first-class PathAdvisorChangeProposal type for enforcing the
 * non-ChatGPT guidance model. PathAdvisor must GUIDE, EXPLAIN, JUSTIFY, and
 * REVIEW — never silently rewrite user content.
 *
 * ============================================================================
 * WHY CHANGE PROPOSALS EXIST (CRITICAL CONTRACT)
 * ============================================================================
 *
 * PathAdvisor is NOT a ChatGPT-style author.
 *
 * The problem with ChatGPT-style behavior:
 * - User asks "improve my resume"
 * - AI silently rewrites entire sections
 * - User has no visibility into WHAT changed or WHY
 * - Trust is broken because user doesn't understand or control the changes
 *
 * PathAdvisor's guidance model:
 * - User asks "review my resume"
 * - PathAdvisor shows WHAT changed (before/after)
 * - PathAdvisor shows WHY it changed (explicit justification)
 * - PathAdvisor shows WHAT it maps to (USAJOBS req, OPM norm, GS-level expectation)
 * - User decides whether to apply the change
 *
 * This contract is enforced by UI + data model, NOT developer discipline.
 * The ChangeProposalCard component is the ONLY allowed way to present rewrites.
 *
 * ============================================================================
 * DATA MODEL
 * ============================================================================
 *
 * A ChangeProposal captures:
 * 1. WHAT changed: beforeText → afterText
 * 2. WHY it changed: whyText (explicit justification)
 * 3. WHAT it maps to: mapsTo array (federal standards, job requirements)
 * 4. STATUS: shown | applied | dismissed (user decision tracking)
 *
 * ============================================================================
 * WHERE IT FITS IN ARCHITECTURE
 * ============================================================================
 *
 * - Type Layer: Core type definitions for change proposals
 * - Used by: PathAdvisor store (proposals array), ChangeProposalCard (UI)
 * - Rendered in: Focus Mode, Docked Panel, Resume Review Workspace
 * - Integration: Proposals are generated by PathAdvisor AI, stored in state,
 *                displayed in dedicated UI cards, and optionally applied to resume
 *
 * @version Day 43 - Guidance Model + Resume Review Workspace
 */

/**
 * Target type for a change proposal.
 *
 * PURPOSE:
 * Identifies what type of resume content the proposal targets.
 * This enables targeted application of changes to specific resume sections.
 *
 * VALUES:
 * - 'resume-bullet': A specific accomplishment bullet in work experience
 * - 'resume-summary': The resume summary/objective section
 * - 'ksa': A Knowledge, Skills, and Abilities statement
 * - 'cover-letter': Cover letter content
 * - 'other': Any other content type (future extensibility)
 */
export type ChangeProposalTargetType =
  | 'resume-bullet'
  | 'resume-summary'
  | 'ksa'
  | 'cover-letter'
  | 'other';

/**
 * Source type for the "maps to" reference.
 *
 * PURPOSE:
 * Identifies where the change guidance comes from. This is critical for
 * building user trust — they need to know the change isn't arbitrary.
 *
 * VALUES:
 * - 'job': Maps to a specific job requirement from the target job posting
 * - 'usajobs': Maps to USAJOBS resume guidance (e.g., "quantify accomplishments")
 * - 'opm': Maps to OPM qualification standards or guidance
 * - 'gs-norm': Maps to GS-level expectations (e.g., GS-14 expects independent judgment)
 * - 'other': Other authoritative source
 *
 * WHY THIS MATTERS:
 * Users trust changes when they can see the source. "OPM says GS-14 requires..."
 * is more trustworthy than "AI thinks you should...".
 */
export type ChangeProposalMapsToSource =
  | 'job'
  | 'usajobs'
  | 'opm'
  | 'gs-norm'
  | 'other';

/**
 * A single "maps to" reference showing what the change aligns with.
 *
 * PURPOSE:
 * Captures a specific mapping from the change to an authoritative source.
 * Multiple mappings can be provided per proposal.
 *
 * FIELDS:
 * - label: User-facing description of the mapping (e.g., "Quantify impact")
 * - source: Type of authoritative source (usajobs, opm, gs-norm, etc.)
 *
 * EXAMPLES:
 * - { label: 'USAJOBS: quantify accomplishments', source: 'usajobs' }
 * - { label: 'GS-14: independent judgment expected', source: 'gs-norm' }
 * - { label: 'Job req: 3+ years policy analysis', source: 'job' }
 */
export interface ChangeProposalMapsTo {
  /** User-facing description of the mapping */
  label: string;
  /** Type of authoritative source */
  source: ChangeProposalMapsToSource;
}

/**
 * Status of a change proposal.
 *
 * PURPOSE:
 * Tracks what the user decided to do with the proposal. This enables
 * analytics, undo functionality, and UI state management.
 *
 * VALUES:
 * - 'shown': Proposal has been shown to user, no action taken yet
 * - 'applied': User applied the change to their resume
 * - 'dismissed': User dismissed the proposal without applying
 */
export type ChangeProposalStatus = 'shown' | 'applied' | 'dismissed';

/**
 * PathAdvisor Change Proposal.
 *
 * ============================================================================
 * THIS IS THE CORE CONTRACT FOR NON-CHATGPT BEHAVIOR
 * ============================================================================
 *
 * Any resume-related suggestion from PathAdvisor MUST be wrapped in this type.
 * The ChangeProposalCard component is the ONLY UI surface for rendering these.
 * This ensures users always see WHAT changed, WHY, and WHAT it maps to.
 *
 * FIELDS:
 * - id: Unique identifier for this proposal
 * - anchorId: ID of the PathAdvisor anchor this proposal belongs to
 * - targetType: Type of resume content being changed
 * - targetId: Optional ID of the specific item (e.g., work experience ID)
 * - beforeText: Original text (what user wrote)
 * - afterText: Proposed text (what PathAdvisor suggests)
 * - whyText: Explicit justification for the change
 * - mapsTo: Array of authoritative source mappings
 * - status: Current status (shown, applied, dismissed)
 * - createdAt: Timestamp when proposal was created
 *
 * EXAMPLE:
 * ```typescript
 * const proposal: PathAdvisorChangeProposal = {
 *   id: 'proposal-1234567890',
 *   anchorId: 'anchor-1234567890-resume',
 *   targetType: 'resume-bullet',
 *   targetId: 'work-exp-1-accomplishment-2',
 *   beforeText: 'Led team meetings',
 *   afterText: 'Led weekly team meetings for 12-person cross-functional team, reducing project delays by 25% through improved coordination',
 *   whyText: 'Federal resumes require quantified accomplishments with scope and measurable outcomes. "Led team meetings" lacks specificity.',
 *   mapsTo: [
 *     { label: 'USAJOBS: quantify accomplishments', source: 'usajobs' },
 *     { label: 'GS-14: scope and impact expected', source: 'gs-norm' },
 *   ],
 *   status: 'shown',
 *   createdAt: Date.now(),
 * };
 * ```
 */
export interface PathAdvisorChangeProposal {
  /** Unique identifier for this proposal */
  id: string;
  /** ID of the PathAdvisor anchor this proposal belongs to */
  anchorId: string;
  /** Type of resume content being changed */
  targetType: ChangeProposalTargetType;
  /** Optional ID of the specific item (e.g., work experience ID, bullet index) */
  targetId?: string;
  /** Original text (what user wrote) */
  beforeText: string;
  /** Proposed text (what PathAdvisor suggests) */
  afterText: string;
  /** Explicit justification for the change */
  whyText: string;
  /** Array of authoritative source mappings (what the change aligns with) */
  mapsTo: ChangeProposalMapsTo[];
  /** Current status (shown, applied, dismissed) */
  status: ChangeProposalStatus;
  /** Timestamp when proposal was created (milliseconds since epoch) */
  createdAt: number;
}

/**
 * Generates a unique proposal ID.
 *
 * PURPOSE:
 * Creates deterministic unique identifiers for proposals.
 * Uses timestamp + random suffix for collision resistance.
 *
 * FORMAT:
 * "proposal-{timestamp}-{random}"
 *
 * @returns Unique proposal ID string
 */
export function createProposalId(): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8);
  return `proposal-${timestamp}-${random}`;
}

/**
 * Normalizes the mapsTo array to ensure valid entries.
 *
 * PURPOSE:
 * Validates and cleans up mapsTo entries before storing.
 * Filters out invalid entries (empty labels) and ensures consistent format.
 *
 * BEHAVIOR:
 * - Removes entries with empty/whitespace-only labels
 * - Trims whitespace from labels
 * - Preserves order of entries
 *
 * @param mapsTo - Array of mapsTo entries to normalize
 * @returns Normalized array with valid entries only
 */
export function normalizeMapsTo(
  mapsTo: ChangeProposalMapsTo[]
): ChangeProposalMapsTo[] {
  const normalized: ChangeProposalMapsTo[] = [];

  for (let i = 0; i < mapsTo.length; i++) {
    const entry = mapsTo[i];
    const trimmedLabel = entry.label.trim();

    if (trimmedLabel !== '') {
      normalized.push({
        label: trimmedLabel,
        source: entry.source,
      });
    }
  }

  return normalized;
}

/**
 * Creates a new proposal with default values.
 *
 * PURPOSE:
 * Factory function for creating proposals with sensible defaults.
 * Ensures all proposals have valid IDs, timestamps, and status.
 *
 * USAGE:
 * ```typescript
 * const proposal = createProposal({
 *   anchorId: 'anchor-123',
 *   targetType: 'resume-bullet',
 *   beforeText: 'Led team meetings',
 *   afterText: 'Led weekly meetings for 12-person team...',
 *   whyText: 'Federal resumes require quantified accomplishments',
 *   mapsTo: [{ label: 'USAJOBS: quantify accomplishments', source: 'usajobs' }],
 * });
 * ```
 *
 * @param params - Partial proposal params (id, status, createdAt optional)
 * @returns Complete PathAdvisorChangeProposal
 */
export function createProposal(
  params: Omit<PathAdvisorChangeProposal, 'id' | 'status' | 'createdAt'> & {
    id?: string;
    status?: ChangeProposalStatus;
    createdAt?: number;
  }
): PathAdvisorChangeProposal {
  return {
    id: params.id || createProposalId(),
    anchorId: params.anchorId,
    targetType: params.targetType,
    targetId: params.targetId,
    beforeText: params.beforeText,
    afterText: params.afterText,
    whyText: params.whyText,
    mapsTo: normalizeMapsTo(params.mapsTo),
    status: params.status || 'shown',
    createdAt: params.createdAt || Date.now(),
  };
}
