/**
 * ============================================================================
 * JOB DATA MODEL -- Local-only job search types
 * ============================================================================
 *
 * BOUNDARY RULE: This file MUST NOT import from next/* or electron/*.
 *
 * TRUST-FIRST: No scraping, no auto-apply. Jobs are either user-entered
 * or loaded from a local mock dataset for development.
 */

// ---------------------------------------------------------------------------
// Job model (stable fields)
// ---------------------------------------------------------------------------

/**
 * Status category for Saved Jobs workspace metrics and card tags.
 * Used for Ready to Apply, Needs Review, High Match, Backup counts and display.
 */
export type SavedJobStatus = 'ready' | 'needs-review' | 'high-match' | 'backup';

export interface Job {
  /** Unique local ID (generated by storage helpers) */
  id: string;
  /** Job title */
  title: string;
  /** Federal agency name */
  agency: string;
  /** Duty location(s) */
  location: string;
  /** GS grade or pay band (optional) */
  grade?: string;
  /** Salary range string (optional) */
  salaryRange?: string;
  /** USAJOBS URL or announcement link (optional) */
  url?: string;
  /** Short summary or description (optional) */
  summary?: string;
  /** ISO 8601 timestamp when saved locally */
  savedAt: string;
  /** Match score 0–100 when available (e.g. from local analysis). Optional. */
  matchScore?: number;
  /** Application close date (e.g. "Mar 18, 2026" or ISO). Optional. */
  closeDate?: string;
  /** Telework eligibility (e.g. "Telework", "Remote"). Optional. */
  telework?: string;
  /** Appointment type (e.g. "Permanent", "Term"). Optional. */
  appointmentType?: string;
  /** Status for Saved Jobs metrics and card tags. Optional. */
  status?: SavedJobStatus;
}

// ---------------------------------------------------------------------------
// Store shape
// ---------------------------------------------------------------------------

export const JOB_SEARCH_SCHEMA_VERSION = 1;

export interface JobSearchStore {
  schemaVersion: number;
  savedJobs: Job[];
  /** ID of the currently selected/viewed job */
  selectedJobId: string | null;
  /** Last search query (for state restoration) */
  lastSearchQuery: string;
}

// ---------------------------------------------------------------------------
// Mock dataset (local-only, for development)
// ---------------------------------------------------------------------------

export function createMockJobs(): Job[] {
  const now = new Date().toISOString();
  return [
    {
      id: 'mock-1',
      title: 'IT Specialist (INFOSEC)',
      agency: 'Department of Homeland Security',
      location: 'Washington, DC',
      grade: 'GS-13',
      salaryRange: '$90,893 - $118,161',
      url: 'https://www.usajobs.gov/job/825742100',
      summary: 'Serves as an IT Specialist responsible for planning, implementing, and maintaining information security programs and policies.',
      savedAt: now,
    },
    {
      id: 'mock-2',
      title: 'Management Analyst',
      agency: 'Office of Personnel Management',
      location: 'Washington, DC',
      grade: 'GS-12',
      salaryRange: '$76,459 - $99,404',
      url: 'https://www.usajobs.gov/job/825110200',
      summary: 'Performs organizational studies and evaluations, designs systems and procedures, and conducts management reviews.',
      savedAt: now,
    },
    {
      id: 'mock-3',
      title: 'Program Analyst',
      agency: 'Department of Veterans Affairs',
      location: 'Remote',
      grade: 'GS-11',
      salaryRange: '$63,795 - $82,932',
      url: 'https://www.usajobs.gov/job/824985300',
      summary: 'Analyzes program operations and provides recommendations for improving organizational effectiveness.',
      savedAt: now,
    },
    {
      id: 'mock-4',
      title: 'Budget Analyst',
      agency: 'Department of Defense',
      location: 'Arlington, VA',
      grade: 'GS-12',
      salaryRange: '$76,459 - $99,404',
      url: 'https://www.usajobs.gov/job/824876100',
      summary: 'Formulates budget estimates, justifications, and execution reports for assigned programs and projects.',
      savedAt: now,
    },
    {
      id: 'mock-5',
      title: 'Human Resources Specialist',
      agency: 'Department of the Interior',
      location: 'Denver, CO',
      grade: 'GS-11',
      salaryRange: '$63,795 - $82,932',
      url: 'https://www.usajobs.gov/job/824512400',
      summary: 'Provides HR advisory services in staffing, classification, and employee relations for the regional office.',
      savedAt: now,
    },
    {
      id: 'mock-6',
      title: 'Contract Specialist',
      agency: 'General Services Administration',
      location: 'Kansas City, MO',
      grade: 'GS-12',
      salaryRange: '$76,459 - $99,404',
      url: 'https://www.usajobs.gov/job/824321700',
      summary: 'Plans, negotiates, awards, and administers contracts for supplies and services.',
      savedAt: now,
    },
  ];
}
